stages:
  - test
  - pages
  - fetch-version

before_script:
  - git fetch --tags

pytest:
  image: python:3.8
  stage: test
  script:
    - pip install pytest pytest-cov numpy scipy scikit-image
    - pytest --cov=src/ --cov-config=.coveragerc --cov-report=html --cov-report=xml --junitxml=report.xml
  artifacts:
    when: always
    paths:
    - htmlcov/
    reports:
      junit: report.xml
      cobertura: coverage.xml

pages:
  stage: pages
  script:
  - mv htmlcov/ public
  artifacts:
    paths:
    - public
  only:
    - master
    - /^release-.*$/

fetch-semantic-version:
  # Requires Node >= 10.13 version
  image: node:13
  stage: fetch-version
  only:
    refs:
    - master
    - /^release-.*$/
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release
