stages:
  - test
  - pages
  - fetch-version

before_script:
  - git fetch --tags

pytest:
  image: python:3.7
  stage: test
  script:
    - apt update
    - apt install -y libgl1-mesa-glx
    - pip install pytest pytest-cov numpy scipy scikit-image pdoc3==0.8.1
    - pytest --cov=src/ --cov-config=.coveragerc --cov-report=html --cov-report=xml --junitxml=report.xml
    - pdoc3 src/QbiPy --html --force
  artifacts:
    when: always
    paths:
    - htmlcov/
    - html/
    reports:
      junit: report.xml
      cobertura: coverage.xml

pages:
  stage: pages
  script:
  - mkdir public/other
  - mv htmlcov/ public/other
  - mv html/QbiPy public
  artifacts:
    paths:
    - public
  only:
    - master
    - /^release-.*$/

fetch-semantic-version:
  # Requires Node >= 10.13 version
  image: node:13
  stage: fetch-version
  only:
    refs:
    - master
    - /^release-.*$/
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release
