stages:
  - test
  - pages
  - fetch-version
  - deploy

before_script:
  - git fetch --tags

pytest:
  image: registry.gitlab.com/manchester_qbi/manchester_qbi_public/qbipy/qbipy_depends
  stage: test
  script:
    - pip install configargparse pydicom
    - pytest --cov=src/ --cov-config=.coveragerc --cov-report=html --cov-report=xml --junitxml=report.xml
    - pdoc3 src/QbiPy --html --force
  artifacts:
    when: always
    paths:
    - htmlcov/
    - html/
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pages:
  stage: pages
  script:
  - mkdir public
  - mkdir public/test_coverage
  - mv htmlcov/* public/test_coverage/
  - mv html/QbiPy/* public/
  artifacts:
    paths:
    - public
  only:
    - master
    - /^release-.*$/

fetch-semantic-version:
  # Requires Node >= 14.17 version
  image: node:16
  stage: fetch-version
  only:
    refs:
    - master
    - /^release-.*$/
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release

pypi_release:
  image: registry.gitlab.com/manchester_qbi/manchester_qbi_public/qbipy/qbipy_depends
  stage: deploy
  cache: {}
  script:
    - pip install -U twine
    - ./version.sh
    - python setup.py sdist bdist_wheel
    - twine check dist/*
    # upload to oficial
    - twine upload dist/*
  only:
    - /^release-.*$/
