stages:
  - test
  - pages
  - fetch-version

before_script:
  - git fetch --tags

pytest:
  image: registry.gitlab.com/manchester_qbi/manchester_qbi_public/qbipy/qbipy_depends
  stage: test
  script:
    - pytest --cov=src/ --cov-config=.coveragerc --cov-report=html --cov-report=xml --junitxml=report.xml
    - pdoc3 src/QbiPy --html --force
  artifacts:
    when: always
    paths:
    - htmlcov/
    - html/
    reports:
      junit: report.xml
      cobertura: coverage.xml

pages:
  stage: pages
  script:
  - mkdir public
  - mkdir public/test_coverage
  - mv htmlcov/* public/test_coverage/
  - mv html/QbiPy/* public/
  artifacts:
    paths:
    - public
  only:
    - master
    - /^release-.*$/

fetch-semantic-version:
  # Requires Node >= 10.13 version
  image: node:13
  stage: fetch-version
  only:
    refs:
    - master
    - /^release-.*$/
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release
  artifacts:
    paths:
    - VERSION.txt
