stages:
  - test
  - fetch-version

before_script:
  - git fetch --tags

pytest:
  image: python:3.7
  stage: test
  script:
    - pip install pytest pytest-cov numpy scipy scikit-image
    - pytest --junitxml=report.xml --cov=src/ 
    - coverage xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      cobertura: coverage.xml

fetch-semantic-version:
  # Requires Node >= 10.13 version
  image: node:13
  stage: fetch-version
  only:
    refs:
    - master
    - /^release-.*$/
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release
